server:
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: bns-ssl
  port: 9090

spring:
  application:
    name: seanlee-kakaomapTest
  sql:
    init:
      encoding: UTF-8
      mode: always
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:xe
    username: kakaomaptest
    password: kakaomaptest
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
#      ddl-auto: none
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace